version: "3.7"

services:
  caddy:
    image: caddy:latest
    network_mode: host
    ports:
      - "80:8080"
      - "443:443"
      - "443:443/udp"
    volumes:
      - $PWD/remote/production/Caddyfile:/etc/caddy/Caddyfile
